import os

if not config:
    default_config = "config/config.yaml"
    if not os.path.exists(default_config):
        raise SystemExit(
            "config/config.yaml not found.\n"
            "Either pass --configfile /path/to/config.yaml or copy the template:\n"
            "  cp config/config.yaml.template config/config.yaml"
        )
    configfile: default_config


include: "rules/common.smk"
include: "rules/split.smk"
include: "rules/sortmerna.smk"
include: "rules/fastp.smk"
include: "rules/join.smk"
include: "rules/qc.smk"
include: "rules/star.smk"
include: "rules/rsem.smk"
include: "rules/salmon.smk"


rule all:
    input:
        get_fastqc_outputs,
        get_fastqc_trimmed_outputs,
        f"{config['output_dir']}/multiqc/multiqc_report.html",
        expand(
            f"{config['output_dir']}/star/{{sample}}/{{sample}}Aligned.sortedByCoord.out.bam",
            sample=SAMPLES,
        ),
        expand(
            f"{config['output_dir']}/star/{{sample}}/{{sample}}Aligned.toTranscriptome.out.bam",
            sample=SAMPLES,
        ),
        expand(
            f"{config['output_dir']}/star/{{sample}}/{{sample}}ReadsPerGene.out.tab",
            sample=SAMPLES,
        ),
        expand(
            f"{config['output_dir']}/rsem/{{sample}}.genes.results", sample=SAMPLES
        ),
        expand(
            f"{config['output_dir']}/rsem/{{sample}}.isoforms.results", sample=SAMPLES
        ),
        expand(
            f"{config['output_dir']}/salmon/{{sample}}/quant.sf", sample=SAMPLES
        ),
        expand(
            f"{config['output_dir']}/salmon/{{sample}}/quant.genes.sf", sample=SAMPLES
        ),


rule preprocessing:
    input:
        get_fastqc_outputs,
        get_fastqc_trimmed_outputs,
